# Generated by Django 5.0.1 on 2024-09-14 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='code',
            name='people_limit',
        ),
        migrations.AddField(
            model_name='code',
            name='use_limit',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='code',
            name='per_person_limit',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('A', 'admin'), ('S', 'shop'), ('U', 'user'), ('P', 'passive')], default='P', max_length=255),
        ),
    ]
