# Generated by Django 5.0.1 on 2024-09-14 11:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_code_people_limit_code_use_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='activates',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 14, 13, 0, 25, 465266, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='code',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 14, 13, 5, 25, 467955, tzinfo=datetime.timezone.utc)),
        ),
    ]
