# Generated by Django 5.0.1 on 2024-09-16 16:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_code_activates_alter_code_expires'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='use_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='code',
            name='activates',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 16, 16, 15, 3, 218238, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='code',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 16, 16, 20, 3, 218238, tzinfo=datetime.timezone.utc)),
        ),
    ]
