FROM python:3.12-slim
WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends gcc && \
    rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN mkdir -p /app/data

EXPOSE 8000
CMD sh -c "python manage.py migrate --noinput && gunicorn szyszkojny.wsgi:application --bind 0.0.0.0:8000 --workers 2"
